mode: production

title: dbp
email: dapoulter@gmail.com
description: audio visual code

baseurl: ""
url: "http://davepoulter.net"

markdown: kramdown

exclude:
  - LICENSE.md
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - config-dev.yml
  - config-prod.yml
